### ISSUE TITLE
will it work for third order categorical features interaction

### ISSUE THREAD

**Issue by Sandy4321** [mosmeh/ifm#1]
Great code,  thanks !

Plese help to understand
1
will it work for third order categorical features interaction ?
2
will it run on Windows computer ?

3
will it work for sparse data ?

**Comment by mosmeh** [comment]
As this is the code I wrote a few years ago and it seems I didn't leave any proper description, I might give the wrong answer, but I'll try:

First of all, this is an implementation of Incremental Factorization Machines, proposed in https://arxiv.org/abs/1607.02858

> will it work for third order categorical features interaction ?

The dataset the author tested it on (ML100k) seems to include categorical features, so it should work with categorical features. However, the interactions are up to second-order, as with an ordinary factorization machine.

> will it run on Windows computer ?

Since it depends only on numpy, it should.

> will it work for sparse data ?

Incremental Factorization Machines was proposed for item recommendation, and recommendation datasets are usually sparse, so I expect it to work for sparse data.

**Comment by Sandy4321** [comment]
do you know about fresh fast implementations for example from
https://github.com/takuti

how fast your code is?

**Comment by mosmeh** [comment]
> do you know about fresh fast implementations for example from https://github.com/takuti

None that I know of.
Maybe [FluRS](https://takuti.me/note/flurs/)? (sorry if it's totally unrelated)

> how fast your code is?

I don't know how fast you want my code to be. You can always start with small datasets and optimize the code if you find it slow.

**Comment by Sandy4321** [comment]
by the way 
may you kindly recommend several data sets to try with your FM code 
especially one for just classification , not recsys?
